export const Menu =[
    {
        title:soko,
        Path:'./',
        className:'sokougali'
    },
    {
        title:soko,
        Path:'./',
        className:'Amaize'
    },
     {
        title:soko,
        Path:'./',
        className:'ranee'
    },
    {
        title:soko,
        Path:'./',
        className:'cil'
    },
    {
        title:soko,
        Path:'./',
        className:'pearl'
    },
    {
        title:soko,
        Path:'./',
        className:'yola'
    },
    {
        title:soko,
        Path:'./',
        className:'treatos'
    },
]